spring:
  # jpa配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      dialect:
        sqlite: org.sqlite.hibernate.dialect.SQLiteDialect
        h2: org.hibernate.dialect.H2Dialect
  # h2配置
  h2:
    console:
      # 启用控制台
      enabled: true
      path: /h2
      settings:
        # 允许外人连接
        web-allow-others: true
        # 配置h2首选项时的账号密码
        web-admin-password: test
  datasource:
    # h2
    h2:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:file:./h2.db
      username: root
      password: meethigher
    # sqlite
    sqlite:
      driver-class-name: org.sqlite.JDBC
      jdbc-url: jdbc:sqlite:./sqlite.db
